# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flask-otel-app
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: flask-otel-app
#   template:
#     metadata:
#       labels:
#         app: flask-otel-app
#     spec:
#       containers:
#       - name: flask-otel-app
#         image: jatin560/flask-otel-app:v3
#         ports:
#           - containerPort: 5000
#         env:
#           - name: OTEL_EXPORTER_OTLP_ENDPOINT
#             # value: "http://tempo-distributor.tempo.svc.cluster.local:4318/v1/traces"
#             value: "http://tempo-gateway.tempo.svc.cluster.local/otlp/v1/traces"


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: tempo-traces-flask-app
#   namespace: default
#   labels:
#     app.kubernetes.io/name: tempo-traces-flask-app # <--- IMPORTANT: This label matches service.name in OTel
#     app.kubernetes.io/instance: tempo-traces-flask-app-instance
#     app.kubernetes.io/version: "1.0.0"
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: tempo-traces-flask-app
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: tempo-traces-flask-app
#         app.kubernetes.io/instance: tempo-traces-flask-app-instance
#         app.kubernetes.io/version: "1.0.0"
#     spec:
#       containers:
#       - name: tempo-traces-flask-app-container
#         image: jatin560/tempo-traces-flask-app:v3
#         ports:
#         - containerPort: 5000
#           name: http
#         env:
#         - name: OTEL_LOGS_EXPORTER
#           value: "none"
#         # --- OpenTelemetry Configuration ---
#         - name: OTEL_TRACES_EXPORTER
#           value: "otlp_proto_grpc"
#         - name: OTEL_EXPORTER_OTLP_PROTOCOL
#           value: "grpc"
#         - name: OTEL_EXPORTER_OTLP_ENDPOINT
#           value: "http://grafana-alloy.alloy-logs.svc.cluster.local:4317"
#         - name: OTEL_EXPORTER_OTLP_INSECURE
#           value: "true"
#         - name: OTEL_RESOURCE_ATTRIBUTES
#           value: "service.name=tempo-traces-flask-app,service.version=1.0.0,service.environment=dev,k8s.namespace.name=$(K8S_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.node.name=$(NODE_NAME)"
#         # --- Downward API for K8s Resource Attributes ---
#         - name: K8S_NAMESPACE
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.namespace
#         - name: POD_NAME
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.name
#         - name: NODE_NAME
#           valueFrom:
#             fieldRef:
#               fieldPath: spec.nodeName
#         - name: CONTAINER_NAME
#           value: flask-container
